version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
